	#|--------------Getters--------------|#
		#this is where a list of getters will go...
	#def get_...
		"""GETTERS"""


	#|--------------Setters--------------|#
		#this is where a list of setters will go...
	#def set_...
		"""SETTERS"""
